title: "我的项目"
description: ""
baseurl: ""
url: "https://wolffy1998.github.io/"

# 添加导航链接（会显示在页面顶部导航栏）
nav:
  - title: "首页"
    url: /
  - title: "关于"  # 新增关于页导航
    url: /about/

theme: jekyll-theme-architect 
